# Generated by Django 4.0.4 on 2023-02-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='email_id',
            new_name='email',
        ),
    ]
